sudo: required
language: android
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
os:
- linux
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.1
  - android-29 - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - addon-google_apis-google-29
  - sys-img-armeabi-v7a-google_apis-29
  - extra-google-android-support
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_install:
- openssl aes-256-cbc -K $encrypted_591be3b350cb_key -iv $encrypted_591be3b350cb_iv
  -in mood.jks.enc -out mood.jks -d
- git clone -b master https://github.com/flutter/flutter.git
- export PATH="$PATH:$PWD/flutter/bin/"
- flutter channel stable
- flutter upgrade
- wget http://services.gradle.org/distributions/gradle-4.10.2-all.zip
- unzip gradle-4.10.2-all.zip
- export GRADLE_HOME=$PWD/gradle-4.10.2-all
- export PATH=$GRADLE_HOME/bin:$PATH
script:
- "./flutter/bin/flutter upgrade"
- "./flutter/bin/flutter -v build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key:
    secure: qxVz66a2nUar3qFQWysslQdq1WJleBBT7QddbKWF6OQrC34BLX9Hzt591+qBP2Glr9fbrEOSdmkiKctRw5gkWNmKd9H5DmsCZoLwLiWGoJVP+2LHvbp0WyPnO0KmzEzvdyZ6uX7/2EdGLY1YbeYODmkgNyW/o6pTk3bvivtAd5rsO/BzMwrW1nZm90AbvUlNXravFfGMtgBvCreBjVimmPfS/KcUafUuf5Xc1R9hm6a0RSGmsWgJcDKyiwku76SY/OhwdyP1/9xsmKLyMk8EHiCAKSqOupaW41/xNiIeyBz6RbwgOmHk+0OYfOwGXSqradK9shHfQlZu4G0G6n69l2nsYumFxzXEjEn7DXenPRyoGfeqZjFrqYxUq9Y0NIKBQ+T1NWfVrbNSHL4uWAwAHzzI/X1426shjF1jmDsqt025fmCqgGYa6WjWCNx4nnkBpnlv/KS4knIQm/YD7Qf5VKkHdB92UhNO4xA8elEf50INJcpGrlmac6tdpvcyFiPkbgjgJlb3J83yIpx18U7xY8eg6u2EpEsxiYByyOdH8qDAOP4WroGmhOfJB2s0ic6pyPmtIzhjStzUrFUJZsAKayWFJWNPDJJXj5tInT1iBH1m8GJ1EaZYOWfRYqKtV+CoGVT32NW+DkqK3haCcaFytnWtWomuBVST+GjOxmDRDAc=
  file: build/app/outputs/apk/release/app-release.apk
  on:
    repo: microtears/Mood
